# Generated by Django 5.2.6 on 2025-09-09 15:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('jersey', 'Jersey Bola'), ('shoes', 'Sepatu Bola'), ('ball', 'Bola'), ('accessories', 'Aksesoris'), ('training', 'Alat Latihan'), ('jacket', 'Jaket')], default='update', max_length=50)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0)),
                ('sold', models.PositiveIntegerField(default=0)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
