# Generated by Django 5.2.6 on 2025-09-12 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Product',
        ),
    ]
