# Generated by Django 5.2.6 on 2025-09-25 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
